version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    expose: 
      - "8000"
    volumes:
      - .:/app
    stdin_open: true
    env_file:
      - .env

    depends_on:
      - pgdb
      - mongodb


  pgdb:
      image: postgres:15
      restart: always
      env_file:
        - .env.postgres

      volumes:
          - pgdb-data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - "5055:80"
    logging:
      driver: none
      
  
  mongodb:
      image: mongo:7
      restart: always
      ports:
        - '27017:27017'
      volumes:
        - mongodb-data:/var/lib/mongodb/data


volumes:
  pgdb-data:
  mongodb-data:
  
networks:
  db_network: