# Generated by Django 3.2.23 on 2024-01-17 22:53

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='barcode',
            field=models.CharField(max_length=13, validators=[book.validators.validate_barcode]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, validators=[book.validators.validate_isbn]),
        ),
    ]
