# Generated by Django 3.2.23 on 2024-01-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20240117_2241'),
        ('book', '0002_auto_20240117_2253'),
    ]

    operations = [
    ]
